---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "SDS348 Fall 2019"
date: "November 26, 2019 "
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
```
## Cara (Yijin)Zou

# Modeling

```{R}
library(tidyverse)
TB_Data<-read.csv("/Users/yijinzou/Desktop/SDS348Site/content/TB_Data.csv", header=T)%>%dplyr::select(-1, -Country.Code)

```
# Introduction 
This dataset is comprised of a merged dataset from [World Health Organization](https://www.who.int/tb/country/data/download/en/) and [The World Bank Group](https://data.worldbank.org/indicator/NY.GDP.PCAP.CD). It consists of information about cases of Tuberculosis including new pulmonary cases, previous cases, drug resistant cases (MDR and XDR), mortality due to tuberculosis, etc. This dataset also contains information about country, region, year (2017 or 2018), population number, and GDP per capita in US dollars. 


# MANOVA testing
```{R}
 #H0: For each response variable, the means of the groups are equal
 #H1: For at least one response variable, at least one group mean differs
head(TB_Data)
man1<-manova(cbind(new.pul.TB,prev.treated.pul.TB,prev.unk.pul.TB, new.MDR, prev.MDR, XDR, pop.number, TB.100k, TB_mort.100k, GDP)~region, data=TB_Data)
summary(man1)

```
There are alot of assumptions for the MANOVA test which indicates that they are usually hard to test and/or meet. These assumptions include: random samples, independent observations, dependent variables have multivariate normality, homogeneity of within-group covariance matrices for each dependent variable and equal covariance between any two dependent variables, linear relationships amoung dependent variables, no extreme univariate or multivariate outliers, and no multicollinearity. The dataset would likely not have been able to meet the assumptions, especially since many of the variables are likely correlated (e.g.: new drug resistant TB cases is likely related to previous/new TB cases ). 

For the MANOVA, only 10 dependent variables were chosen. For example, only one of TB.100k (TB cases per 100,000 people) and TB.num (TB cases total) since they are likely to be highly related. The p-value (< 2.2e-16) is significant for the MANOVA test, therefore, for at least one of the response variables, the mean between regions is different. 

## Univariate ANOVA testing
```{R}
summary.aov(man1)
```
Of the 10 dependent variables tested, the univariate ANOVAs with a p-value <0.05 include: new.pul.TB, prev.treated.pul.TB, prev.unk.pul.TB, pop.number, TB.100k, TB_mort.100k, and GDP. 


## Post hoc t-testing
```{R}

# region in world: AFR=Africa; AMR=Americas;
# EMR=Eastern Mediterranean; EUR=Europe; SEAR=South-East
# Asia; WPR=Western Pacific

#New pulmonary tuberculosis cases 
pairwise.t.test(TB_Data$new.pul.TB,TB_Data$region,p.adj="none")

#Previously treated pulmonary tuberculosis cases 
pairwise.t.test(TB_Data$prev.treated.pul.TB,TB_Data$region,p.adj="none")

#Confirmed pulmonary TB cases with unknown TB treatment history
pairwise.t.test(TB_Data$prev.unk.pul.TB,TB_Data$region,p.adj="none")

#Population Number 
pairwise.t.test(TB_Data$pop.number,TB_Data$region,p.adj="none")

#TB cases per 100,000 individuals
pairwise.t.test(TB_Data$TB.100k,TB_Data$region,p.adj="none")

#TB mortality cases per 100,000 individuals 
pairwise.t.test(TB_Data$TB_mort.100k,TB_Data$region,p.adj="none")

#GDP 
pairwise.t.test(TB_Data$GDP,TB_Data$region,p.adj="none")

```

## Bonferroni correction 
```{R}
#MANOVA: 1 
#ANOVA: 11
#T-tests: 15* 7= 105

#Probability of a type I error if unadjusted 
1-(1-0.05)^117

#New alpha 
0.05/(1+10+105)


```
The total number of tests conducted is 117, therefore if unadjusted, the probability of at least one type I error is 0.9975. Therefore, the bonferroni correction was used to obtain the new alpha value of 0.00043 so that the overall alpha value remains at 0.05. 


Using this new alpha value, the MANOVA is still significant. The ANOVAs of new.pul.TB, prev.treated.pul.TB, pop.number, TB.100k, TB_mort.100k, and GDP are still significant. Only the ANOVA of prev.unk.pul.TB is no longer significant (p-value=0.005189). For the post-hoc analysis of the new pulmonary TB cases, previously treated pulmonary TB, and population number only the means of SEA are different from the other regions. For TB.100k there are significant differences between AFR/AMR, AFR/EMR, AFR/EUR, AMR/SEA, AMR/WPR, SEA/EMR, EUR/SEA, and EUR/WPR. For the TB mortality for every 100,000 individuals, AFR is significantly different from the other regions. For GDP, AFR/EMR, AFR/EUR, AFR/WPR,  AMR/EUR, EUR/SEA, and EUR/WPR are significantly different. 


# Randomization test: PERMANOVA 

```{R}
#H0: The centroid and dispersion of points is the same for the different regions
#H1: The centroid and dispersion of points is different for at least one of the different regions


#compute distances/dissimilarities
dists<-TB_Data%>%dplyr::select(new.pul.TB,prev.treated.pul.TB,prev.unk.pul.TB, new.MDR, prev.MDR, XDR, pop.number, TB.100k, TB_mort.100k, GDP)%>%dist()


#compute observed F
SST<- sum(dists^2)/150
SSW<-TB_Data%>%group_by(region)%>%dplyr::select(new.pul.TB,prev.treated.pul.TB,prev.unk.pul.TB, new.MDR, prev.MDR, XDR, pop.number, TB.100k, TB_mort.100k, GDP)%>%
 do(d=dist(.[2:3],"euclidean"))%>%ungroup()%>%
 summarise(sum(d[[1]]^2)/50 + sum(d[[2]]^2)/50+ sum(d[[3]]^2)/50)%>%pull
F_obs<-((SST-SSW)/2)/(SSW/147) #observed F statistic
F_obs


# compute null distribution for F
Fs<-replicate(1000,{
new<-TB_Data%>%mutate(region=sample(region)) #permute the region vector
SSW<-new%>%group_by(region)%>%dplyr::select(new.pul.TB,prev.treated.pul.TB,prev.unk.pul.TB, new.MDR, prev.MDR, XDR, pop.number, TB.100k, TB_mort.100k, GDP)%>%
 do(d=dist(.[2:3],"euclidean"))%>%ungroup()%>%
 summarise(sum(d[[1]]^2)/50 + sum(d[[2]]^2)/50+ sum(d[[3]]^2)/50)%>%pull
((SST-SSW)/2)/(SSW/147) #calculate new F on randomized data
})

{hist(Fs,prob = T); abline(v=F_obs, col="red", add=T)}

mean(Fs>F_obs)  #p-value 

```
Since the data is unlikely to meet the assumptions of the MANOVA, a randomization-test MANOVA (PERMANOVA) was conducted which resulted in a p-value < 0.05 (significant). Therefore the null hypothesis is rejected in favor of the alternative hypothesis that there is a significant difference between the centroid and/or the spread of the points is not equal between the different regions. This therefore supports the conclusion of the MANOVA conducted previously. 


# Linear regression model
```{R}

TB_Data$GDP_c <- TB_Data$GDP - mean(TB_Data$GDP, na.rm = T)
TB_Data$TB_mort.100k_c <- TB_Data$TB_mort.100k - mean(TB_Data$TB_mort.100k, na.rm = T)
fit1<-lm(TB_mort.100k_c ~ GDP_c*region, data=TB_Data)

#uncorrected SEs
summary(fit1)
```
For the model with uncorrected standard errors, controlling for region, for every increase of 1 USD of GDP from the mean, the number of cases of mortality due to tuberculosis per 100,000 people decreases by 2.858e-03. Compared to the reference region of AFR and controlling for GDP, the mean number of cases of mortality due to tuberculosis per 100,000 people decreases for all regions: AMR (1.472e+01), EMR(6.498e+00), EUR (1.457e+01), SEA (3.136e+01), and WPR (5.678e+00). The coefficient for the interactions describe the difference in the
effect of GDP on the mortality due to tuberculosis per 100,00 people depending on which region the country is in (the slope difference between the regions). For example, the slope difference between AFR and:  AMR (2.651e-03), EMR (2.457e-03), EUR (2.789e-03), SEA (-6.893e-04), and WPR (2.541e-03).  


## Plot the regression
```{R}
TB_Data%>%ggplot(aes(x=GDP_c, y=TB_mort.100k_c,group=region))+geom_point(aes(color=region))+geom_smooth(method = 'lm',se=F, aes(color=region))

```

## Asumptions
```{R}
#Linear relationship between each predictor and response (no scatterplot for region since it is categorical)
ggplot(TB_Data, aes(x=GDP_c, y=TB_mort.100k_c,group=region))+geom_point(aes(color=region))

# Confirm normality of residuals
qqnorm(fit1$residuals, main = "QQ-plot of Model Residuals")
qqline(fit1$residuals, col = "red")

# Confirm equal variance
plot(fit1$fitted.values, fit1$residuals, xlab = "Fitted Values", 
    ylab = "Residuals", pch = 20)
abline(h = 0, col = "red")
library(sandwich); library(lmtest)
bptest(fit1)

```
The data fails all assumptions. The scatterplot does not show a linear relationship between GDP and TB_mort.100k. The QQ-plot of the model residuals is also not normal. There is also a funneling pattern in the residual plot which indicates that it does not meet the assumption of equal variance (homoskedasticity). This is again confirmed by the Breusch-Pagan test which concluded that the homoskedasticity assumption is not met (p-value=1.905e-08).

## Recompute regression results with robust standard errors
```{R}
#robust SEs
coeftest(fit1, vcov = vcovHC(fit1))

```
A model with robust standard errors should be used if the data is heteroskedastic. With uncorrected standard errors, the coefficient estimates of the main effect of GDP (p-value = 0.0162) was significant. The interactions GDP_c:regionAMR (p-value= 0.0472), GDP_c:regionEMR (p-value= 0.0437), GDP_c:regionEUR (p-value= 0.0198), and GDP_c:regionWPR (p-value= 0.0361) were also significant. Contrastingly, using the more robust SEs (more conservative), none of the coefficient estimates are still significant. 

## Effect Size 
```{R}
summary(fit1)$adj.r.squared
```
The adjusted r-squared of 0.356 indicates that 35.6% of variation in the mean number of cases of mortality due to tuberculosis per 100,000 people is explained by the model. 

## Regression but without interactions
```{R}
fit2<-lm(TB_mort.100k_c ~ GDP_c+region, data=TB_Data)
summary(fit2)

```
Examining only the main effects, the effect of GDP is no longer significant while all the coeficient estimates for region are now significant. 

## Linear regression model with bootstrapped standard errors

```{R}


# repeat 5000 times, saving the coefficients each time
samp_distn<-replicate(5000, {
 boot_TB<-TB_Data[sample(nrow(TB_Data),replace=TRUE),]
 fit3<-lm(TB_mort.100k_c ~ GDP_c*region, data=boot_TB)
 coef(fit3)
})

#Estimated SEs
samp_distn%>%t%>%as.data.frame%>%summarise_all(sd)

```
Bootstrapped standard errors are used when the data is non-normal as well. Compared to the original standard errors, the standard errors for all the coefficient estimates increased (more conservative). The p-values are therefore higher as well because of the higher standard errors. Compared to the robust standard errors, the bootstrapped standard errors are also higher. Therefore, the p-values are also higher (more conservative). 


# Logistic regression predicting a binary categorical variable 

```{R}
BinaryTB<-TB_Data%>%mutate(y = as.numeric(ifelse(XDR > 0, 1, 0)))
fit4<-glm(y~region+TB.100k+pop.number,data=BinaryTB,family=binomial(link="logit"))
coeftest(fit4)

exp(coef(fit4))
```
A binary variable was created that measures whether there are any XDR (extensively drug resistant tuberculosis) cases in a country. Controlling for TB.100k and population number, the odds of having a XDR TB case are 1.25 times higher for the region AMR than AFR. The odds for the other regions compared to AFR: EMR (3.47), EUR (9.55), SEA (1.50), WPR (0.79). The region with the lowest odds of a country having a case of XDR TB is WPR. The region that has the highest odds of a country having a case of XDR TB is EUR. Controlling for region and TB.100k, for every 1-unit increase in population number, odds of having a case of XDR TB change by a factor of 1.00000004. Controlling for region and population number, for every 1-unit increase in TB.100k, odds of having a case of XDR TB change by a factor of 1.00545098 (increase by 0.54%). 



## Confusion Matrix
```{R}
prob <- predict(fit4, type = "response") #get predictions
pred <- ifelse(prob > 0.5, 1, 0)
table(truth = BinaryTB$y, prediction = pred) %>% addmargins

#Classification Function
class_diag<-function(probs,truth){

tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]

if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1

#CALCULATE EXACT AUC
ord<-order(probs, decreasing=TRUE)
probs <- probs[ord]; truth <- truth[ord]

TPR=cumsum(truth)/max(1,sum(truth)) 
FPR=cumsum(!truth)/max(1,sum(!truth))

dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)

n <- length(TPR)
auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

data.frame(acc,sens,spec,ppv,auc)
}

class_diag(prob, BinaryTB$y)
```
From the confusion matrix, the model has an accuracy of 0.743 which is fair. The sensitivity or true positive rate is 0.622 which is poor. The specificity or true negative rate is 0.826 which is good. The precision or positive predictive value of the model is 0.709 which is fair. 




## Density of log-odds (logit)  

```{R}
BinaryTB$logit<-predict(fit4) #get predicted log-odds
BinaryTB$factor.y<-factor(BinaryTB$y,levels=c(1,0))
ggplot(BinaryTB,aes(logit, fill=factor.y))+geom_density(alpha=.3)+
  geom_vline(xintercept=0,lty=2)


```
## ROC Curve

```{R}
library(plotROC)
prob <- predict(fit4, type = "response")
ROCplot1 <- ggplot(BinaryTB) + geom_roc(aes(d = y, m = prob),n.cuts = 0)+geom_segment(aes(x=0,xend=1,y=0,yend=1),lty=2) 
ROCplot1

calc_auc(ROCplot1)

```
The AUC is determined to be 0.837 which suggests that the model is good at predicting whether a country has a case of XDR TB (the probability that a randomly selected country with a case of XDR TB has a higher prediction than a randomly selected country without a case of XDR TB). 


## 10-fold CV 
```{R}
k = 10
data1 <- BinaryTB[sample(nrow(BinaryTB)), ] #put dataset in random order
folds <- cut(seq(1:nrow(BinaryTB)), breaks = k, labels = F) #create folds
diags <- NULL
for (i in 1:k) {
# FOR EACH OF 10 FOLDS
train <- data1[folds != i, ] #CREATE TRAINING SET
test <- data1[folds == i, ] #CREATE TESTING SET
truth <- test$y
fit <- glm(y~region+TB.100k+pop.number,data=BinaryTB,family=binomial(link="logit"))
probs <- predict(fit, newdata = test, type = "response")
diags <- rbind(diags, class_diag(probs, truth))
}
apply(diags, 2, mean) #AVERAGE THE DIAGNOSTICS ACROSS THE 10 FOLDS

```
The out of sample confusion matrix for this model has: accuracy (0.742- fair), sensitivity (0.625- poor), specificity (0.811- good), precision (0.692- poor). Although, precision decreased from fair to poor, the classifications did not change greatly. The AUC also did not change significantly which suggests that there was not overfitting. 

# LASSO (least absolute shrinkage and selection operator) Regression
```{R}
head(BinaryTB)
LassoTB<-BinaryTB%>%dplyr::select(region,year,new.pul.TB, prev.treated.pul.TB, prev.unk.pul.TB,new.MDR, prev.MDR, MDR.tested,pop.number, TB.100k, TB.num, TB_mort.100k, TB_mort.num,GDP,y)  

fit5 <- glm(y~.,data=LassoTB,family=binomial(link="logit"))
library(glmnet)
x <- model.matrix(fit5)[, -1]
y <- as.matrix(LassoTB$y)
cv <- cv.glmnet(x, y, family = "binomial")
lasso <- glmnet(x, y, family = "binomial", lambda = cv$lambda.1se)
coef(lasso)

```
Variables with a non-zero coefficient from LASSO will be retained in the model: region, new.MDR, pop.number, TB.100k, and GDP. Therefore, these are the most important predictors of if a country has atleast one case of XDR TB. 


# Perform 10-fold CV using LASSO model
```{R}
#Model with just non-zero lasso coefficient estimates
fit6 <- glm(y ~ region+new.MDR+pop.number+TB.100k+GDP, data = LassoTB, family = "binomial")

prob6 <- predict(fit6, type = "response")
class_diag(prob6, LassoTB$y)


#10-fold CV 
k = 10
data1 <- LassoTB[sample(nrow(LassoTB)), ] #put dataset in random order
folds <- cut(seq(1:nrow(LassoTB)), breaks = k, labels = F) #create folds
diags <- NULL
for (i in 1:k) {
# FOR EACH OF 10 FOLDS
train <- data1[folds != i, ] #CREATE TRAINING SET
test <- data1[folds == i, ] #CREATE TESTING SET
truth <- test$y
fit <- glm(y ~ region+new.MDR+pop.number+TB.100k+GDP, data = LassoTB, family = "binomial")
probs <- predict(fit, newdata = test, type = "response")
diags <- rbind(diags, class_diag(probs, truth))
}
apply(diags, 2, mean) #AVERAGE THE DIAGNOSTICS ACROSS THE 10 FOLDS


```
This new model's out of sample accuracy is 0.797 which is fair. It is slightly higher than the previous model's out of sample accuracy which was 0.743. The AUC also slightly increased from 0.839 to 0.886 (both models are good predictors of if there are XDR TB cases in a country).


```{R, echo=F}
## DO NOT DELETE THIS BLOCK!
sessionInfo()
Sys.time()
Sys.info()
```
