---
title: "Resume/About"
author: "Cara Yijin Zou"
date: "12/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#About Me 
  My name is Cara (Yijin) Zou and I'm currently a junior computational biology major at UT Austin. I'm also a pre-dental student. I'm from Katy, Texas but I've also lived in China, Canada, Malaysia, and Singapore! I'm currently involved in research in the Virtual Drug Screening/Virtual Cures stream where I am trying to identify a potential drug for D-alanine D-alanine ligase (*Mycobacterium tuberculosis*) using both computational and wet lab methods (fun fact: the picture on the home page is a PyMol 3D representation of this enzyme). 

## Education
### Bachelor of Science, Computational Biology   (May 2021)
University of Texas at Austin 

##Interests
Micah 6 Food Pantry Volunteer  (120+ hours)
Origami Circle Officer
Music (Piano, viola, voice)

#Skills
Proficient in Microsoft Office (Word, PowerPoint, and Excel)
Conversational Proficiency in Chinese (Mandarin)
Working knowledge in R code (Packages: Base R, Tidyverse) 
Basic knowledge of Python

#Work Experience
Undergraduate TA for Biostatistics SDS328M (August 2018 – December 2019)
Undergraduate Researcher and Mentor (January 2019 – Present)
Biochemistry (BCH369) PLUS Facilitator (August 2019 – December 2019)

#Accomplishments
College of Natural Sciences 2019 Second Year Excellence Award 
Honorable Texas Pre-Dental Society Member  

#Contact 
[cara.yijin.zou@utexas.edu](cara.yijin.zou@utexas.edu)